### PR TITLE
<feat>(data) add flag for Kosovo

### PR DESCRIPTION
**Pull request by fshiori**
add flag for Kosovo

### CODE REVIEW

**Comment by jimbeck** [comment]
Can we get this merged?

**Comment by matiassingers** [comment]
Thanks so much for this, merging now — apologies for the late reply!

**Comment by ryanbradynd05** [comment]
Could you publish a new version to npm with this included?

**Comment by matiassingers** [comment]
Apologies for the delay here @ryanbradynd05 - I've published 1.3.0 to npm now.

**Pull request merged**
